# Generated by Django 5.2.14 on 2026-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_user_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("like", "Like"), ("chat", "Chat"), ("system", "System")],
                default="system",
                max_length=20,
            ),
        ),
    ]
