# Generated by Django 5.2.14 on 2026-07-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_file_thumbnail'),
        ('users', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User Activity Logs'},
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='status_code',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('project_upload', 'Project Upload'), ('project_like', 'Project Like'), ('project_comment', 'Project Comment')], default='project_upload', max_length=20),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
