# Generated by Django 5.2.14 on 2026-06-01 22:10

import django.core.validators
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_djangoproject_tags_remove_djangoproject_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='project_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpg', 'jpeg', 'png']), projects.models.validate_file_size]),
        ),
    ]
