# Generated by Django 5.2.14 on 2026-07-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomment',
            old_name='text',
            new_name='content',
        ),
    ]
