# Generated by Django 5.2.14 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_rename_text_projectcomment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="file_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="خودکار طور پر منتخب فائلوں کے لیے بنایا جاتا ہے",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
